language: go
go_import_path: vighnesh.org/clamav
go:
- 1.13.x
- master

env:
  - GO111MODULE=on

git:
  depth: 1

install: true

stages:
  - compile
  - test

jobs:
  include:
    - stage: test
      script: skip
